database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
#  dbname: YEVER
  dbname: QQWB
  password: root1234
  type: mysql

sqlite:
  file: './data/sqlite/yever.db'
server:
  addr: 0.0.0.0:8088



