// Code generated by entc, DO NOT EDIT.

package quser

const (
	// Label holds the string label denoting the quser type in the database.
	Label = "quser"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQq holds the string denoting the qq field in the database.
	FieldQq = "qq"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// Table holds the table name of the quser in the database.
	Table = "quser"
)

// Columns holds all SQL columns for quser fields.
var Columns = []string{
	FieldID,
	FieldQq,
	FieldPhone,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
