// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ImagesColumns holds the columns for the "images" table.
	ImagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ImagesTable holds the schema information for the "images" table.
	ImagesTable = &schema.Table{
		Name:       "images",
		Columns:    ImagesColumns,
		PrimaryKey: []*schema.Column{ImagesColumns[0]},
	}
	// QuserColumns holds the columns for the "quser" table.
	QuserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "qq", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
	}
	// QuserTable holds the schema information for the "quser" table.
	QuserTable = &schema.Table{
		Name:       "quser",
		Columns:    QuserColumns,
		PrimaryKey: []*schema.Column{QuserColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "oid", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 120},
		{Name: "age", Type: field.TypeInt},
		{Name: "password", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Size: 120},
		{Name: "phone", Type: field.TypeString, Size: 13, Default: "12345678910"},
		{Name: "description", Type: field.TypeString, Size: 2000, Default: "others"},
		{Name: "created", Type: field.TypeTime},
		{Name: "updated", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WuserColumns holds the columns for the "wuser" table.
	WuserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "phone", Type: field.TypeString},
		{Name: "uid", Type: field.TypeString},
	}
	// WuserTable holds the schema information for the "wuser" table.
	WuserTable = &schema.Table{
		Name:       "wuser",
		Columns:    WuserColumns,
		PrimaryKey: []*schema.Column{WuserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ImagesTable,
		QuserTable,
		UsersTable,
		WuserTable,
	}
)

func init() {
	ImagesTable.Annotation = &entsql.Annotation{
		Table: "images",
	}
	QuserTable.Annotation = &entsql.Annotation{
		Table: "quser",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
	WuserTable.Annotation = &entsql.Annotation{
		Table: "wuser",
	}
}
